using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.IO;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraEditors.Controls;
using DevExpress.Charts;

namespace CarCartelAutoCompany
{
    public partial class MarketingForm : DevExpress.XtraEditors.XtraForm
    {
        public MarketingForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
        }
        private void tileBar_SelectedItemChanged(object sender, TileItemEventArgs e)
        {
            navigationFrame.SelectedPageIndex = tileBarGroupTables.Items.IndexOf(e.Item);
        }                
    
        private void timer1_Tick(object sender, EventArgs e)
        {
            labelTime.Text = DateTime.Now.ToLongTimeString();
            labelDate.Text = DateTime.Now.ToLongDateString();
        }
                  
        SqlConnect sqlConnect = new SqlConnect();     

        void toDoList()
        {
            SqlCommand command = new SqlCommand("Select ID,Subject,Contents from Tbl_ToDoList where PersonnelID=@P1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@P1", textEditIDPersonnel.Text);
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlToDoList.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }
        void campaignList()
        {
            SqlCommand command = new SqlCommand("Select Campaign from Tbl_Campaigns", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlCampaigns.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }
        void saleHistory()
        {
            SqlCommand command = new SqlCommand("select Tbl_Sale.ID,Date,Tbl_Customer.Name+' '+Tbl_Customer.Surname as 'Customer',Tbl_Car.Brand+' '+Tbl_Car.Model as 'Car',Price from Tbl_Sale inner join Tbl_Customer on Tbl_Sale.CustomerID=Tbl_Customer.ID inner join Tbl_Car on Tbl_Sale.CarID=Tbl_Car.ID inner join Tbl_Personnel on Tbl_Sale.PersonnelID=Tbl_Personnel.ID where PersonnelID = @p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlSaleHistory.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }
        void rentedCars()
        {
            SqlCommand command = new SqlCommand("select Tbl_Rent.ID,StartDate,FinishDate,Tbl_Customer.Name+' '+Tbl_Customer.Surname as 'Customer',Brand+' '+Model as 'Car',RentPrice from Tbl_Rent inner join Tbl_Car on Tbl_Rent.CarID = Tbl_Car.ID inner join Tbl_Customer on Tbl_Rent.CustomerID=Tbl_Customer.ID inner join Tbl_Personnel on Tbl_Rent.PersonnelID = Tbl_Personnel.ID where Tbl_Personnel.ID=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlRentedCars.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }
        void receiverList()
        {
            comboBoxReceiverMEssage.Items.Clear();
            SqlCommand command = new SqlCommand("select ID,Name+' '+Surname as 'Personnel' from Tbl_Personnel", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);          
            comboBoxReceiverMEssage.ValueMember = "ID";
            comboBoxReceiverMEssage.DisplayMember = "Personnel";
            comboBoxReceiverMEssage.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }
        void carSelectList()
        {
            SqlCommand command = new SqlCommand("select Model as 'Car',ID from Tbl_Car where vehiclestatus='For Sale'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            comboBoxCarSelect.DataSource = dt;
            comboBoxCarSelect.DisplayMember = "Car";
            comboBoxCarSelect.ValueMember = "ID";
        }
        void carSelectListRent()
        {
            SqlCommand command = new SqlCommand("select Model as 'Car',ID from Tbl_Car where vehiclestatus='For Rent'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            comboBox1.DataSource = dt;
            comboBox1.DisplayMember = "Car";
            comboBox1.ValueMember = "ID";
        }

        LoginScreen loginScreen = new LoginScreen();
        public string perID = "";
        private void MarketingForm_Load(object sender, EventArgs e)
        {          
            
            SqlCommand command = new SqlCommand("Select * from Tbl_Personnel where ID=@P1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@P1", int.Parse(perID));
            SqlDataReader dataReader = command.ExecuteReader();
            while (dataReader.Read())
            {
                textEditIDPersonnel.Text = dataReader[0].ToString();
                textEditName.Text= dataReader[1].ToString();
                textEditSurname.Text= dataReader[2].ToString();
                maskedTextBoxTC.Text= dataReader[4].ToString();
                maskedTextBoxPhone.Text= dataReader[3].ToString();
                textEditEmail.Text= dataReader[5].ToString(); 
                textEditHireDate.Text= dataReader[6].ToString();
                if (dataReader[11] != null)
                {
                    Byte[] data = new Byte[0];
                    data = (Byte[])(dataReader[11]);
                    MemoryStream mem = new MemoryStream(data);
                    pictureBoxPersonnel.Image = Image.FromStream(mem);
                }

            }
            toDoList();
            campaignList();
            saleHistory();
            rentedCars();
            receiverList();
            brandsList();
            fuelTypeList();
            colorList();
            doorList();
            classList();
            carSelectList();
            carSelectListRent();
          


        }

        private void BtnListToDo_Click(object sender, EventArgs e)
        {
            toDoList();
        }

        private void BtnAddToDo_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("Insert into Tbl_ToDoList (Subject,Contents,PersonnelID) values (@p1,@p2,@p3)", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1",textEditSubject.Text);
            command.Parameters.AddWithValue("@p2", richTextBoxContent.Text);
            command.Parameters.AddWithValue("@p3", textEditIDPersonnel.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The new subject added...","Information",MessageBoxButtons.OK,MessageBoxIcon.Information);

        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dataRow = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            textEditSubject.Text = dataRow["Subject"].ToString();
            richTextBoxContent.Text= dataRow["Contents"].ToString();
            lblToDoListID.Text= dataRow["ID"].ToString();
        }

        private void BtnUpdateToDo_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("Update Tbl_ToDoList set Subject=@p1,Contents=@p2 where ID=@p3", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", textEditSubject.Text);
            command.Parameters.AddWithValue("@p2", richTextBoxContent.Text);
            command.Parameters.AddWithValue("@p3", lblToDoListID.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The subject updated...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void BtnDeleteToDo_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("Delete from Tbl_ToDoList where ID=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", lblToDoListID.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The subject deleted...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void rangeTrackBarControl1_EditValueChanged(object sender, EventArgs e)
        {
            if (winExplorerView1.Columns["Price"] == null) return;
            string str = "[Price] >= " + rangeTrackBarControl1.Value.Minimum.ToString() + " AND [Price] <= " + rangeTrackBarControl1.Value.Maximum.ToString();
            winExplorerView1.Columns["Price"].FilterInfo = new ColumnFilterInfo(str);
        }
           
        private void rangeTrackBarControl1_BeforeShowValueToolTip(object sender, TrackBarValueToolTipEventArgs e)
        {
            e.ShowArgs.ToolTip = string.Format("{0:C} - {1:C}", 0, 8000000);
        }
                     
        private void rangeTrackBarControl2_EditValueChanged_1(object sender, EventArgs e)
        {
            if (winExplorerView1.Columns["MotorVolume"] == null) return;
            string str = "[MotorVolume] >= " + rangeTrackBarControl2.Value.Minimum.ToString() + " AND [MotorVolume] <= " + rangeTrackBarControl2.Value.Maximum.ToString();
            winExplorerView1.Columns["MotorVolume"].FilterInfo = new ColumnFilterInfo(str);
        }

        private void rangeTrackBarControl3_EditValueChanged_1(object sender, EventArgs e)
        {

            if (winExplorerView1.Columns["HorsePower"] == null) return;
            string str = "[HorsePower] >= " + rangeTrackBarControl3.Value.Minimum.ToString() + " AND [HorsePower] <= " + rangeTrackBarControl3.Value.Maximum.ToString();
            winExplorerView1.Columns["HorsePower"].FilterInfo = new ColumnFilterInfo(str);
        }

        private void rangeTrackBarControl2_BeforeShowValueToolTip_1(object sender, TrackBarValueToolTipEventArgs e)
        {
            e.ShowArgs.ToolTip = string.Format("{0} - {1}",0,7000);
        }

        private void rangeTrackBarControl3_BeforeShowValueToolTip_1(object sender, TrackBarValueToolTipEventArgs e)
        {
            e.ShowArgs.ToolTip = string.Format("{0} - {1}",0,1000);
        }

        private void btnRecevingMessages_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("select Tbl_Message.ID,MessageSubject,MessageContent,Name+' '+Surname as 'Sender' from Tbl_Message inner join Tbl_Personnel on Tbl_Message.Sender = Tbl_Personnel.ID where Receiver=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1",textEditIDPersonnel.Text);
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlMessageBox.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }

        private void btnSubmittedMEssages_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("select Tbl_Message.ID,MessageSubject,MessageContent,Tbl_Personnel.Name+' '+Tbl_Personnel.Surname as 'Receiver' from Tbl_Message inner join Tbl_Personnel on Tbl_Message.Receiver = Tbl_Personnel.ID  where Sender=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControlSubmiitedMessage.DataSource = dt;
            sqlConnect.sqlConnection().Close();
        }

        private void gridView4_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dataRow = gridView4.GetDataRow(gridView4.FocusedRowHandle);
            comboBoxReceiverMEssage.Text = dataRow["Sender"].ToString();
            txtSubjectMessage.Text = dataRow["MessageSubject"].ToString();
            richTextBoxMsgContent.Text = dataRow["MessageContent"].ToString();
        }

        private void gridView5_FocusedRowChanged_1(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow dataRow = gridView5.GetDataRow(gridView5.FocusedRowHandle);
            comboBoxReceiverMEssage.Text = dataRow["Receiver"].ToString();
            txtSubjectMessage.Text = dataRow["MessageSubject"].ToString();
            richTextBoxMsgContent.Text = dataRow["MessageContent"].ToString();
        }

        private void btnClearMessage_Click(object sender, EventArgs e)
        {
            comboBoxReceiverMEssage.Text = "";
            txtSubjectMessage.Text = "";
            richTextBoxMsgContent.Text = "";
        }

        private void btnSendMessage_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("insert into Tbl_Message (MessageSubject,MessageContent,Receiver,Sender) values (@p1,@p2,@p3,@p4)",sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1",txtSubjectMessage.Text);
            command.Parameters.AddWithValue("@p2", richTextBoxMsgContent.Text);
            command.Parameters.AddWithValue("@p3", comboBoxReceiverMEssage.SelectedValue);
            command.Parameters.AddWithValue("@p4", textEditIDPersonnel.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("Your message has been sent!","Information",MessageBoxButtons.OK,MessageBoxIcon.Information);
        }          
     
         void brandsList()
        {
            SqlCommand command = new SqlCommand("select distinct(Brand) from Tbl_Car where vehiclestatus='For Sale'",sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            checkedListBoxControlBrand.DataSource = dt;
            checkedListBoxControlBrand.DisplayMember = "Brand";
            checkedListBoxControlBrand.ValueMember = "ID";
            
        }
        void fuelTypeList()
        {
            SqlCommand command = new SqlCommand("select distinct(FuelType) from Tbl_Car where vehiclestatus='For Sale'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            checkedListBoxControlFuelType.DataSource = dt;
            checkedListBoxControlFuelType.DisplayMember = "FuelType";
            checkedListBoxControlFuelType.ValueMember = "ID";

        }
        private void classList()
        {
            SqlCommand command = new SqlCommand("select distinct(Class) from Tbl_Car where vehiclestatus='For Sale'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            checkedListBoxControlClass.DataSource = dt;
            checkedListBoxControlClass.DisplayMember = "Class";
            checkedListBoxControlClass.ValueMember = "ID";

        }
        private void colorList()
        {
            SqlCommand command = new SqlCommand("select distinct(Color) from Tbl_Car where vehiclestatus='For Sale'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            checkedListBoxControlColor.DataSource = dt;
            checkedListBoxControlColor.DisplayMember = "Color";
            checkedListBoxControlColor.ValueMember = "ID";

        }
        private void doorList()
        {
            SqlCommand command = new SqlCommand("select distinct(NumberofDoors) from Tbl_Car where vehiclestatus='For Sale'", sqlConnect.sqlConnection());
            SqlDataAdapter da = new SqlDataAdapter(command);
            DataTable dt = new DataTable();
            da.Fill(dt);
            checkedListBoxControlDoors.DataSource = dt;
            checkedListBoxControlDoors.DisplayMember = "NumberofDoors";
            checkedListBoxControlDoors.ValueMember = "ID";

        }       

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            //Rental
            chartControl1.Series["Months"].Points.Clear();
            SqlCommand command1 = new SqlCommand("select COUNT(CarID) as 'Total Rent',Month+' '+Year as 'Income Period',IncomeID from Tbl_Rent inner join Tbl_Income on Tbl_Rent.IncomeID = Tbl_Income.ID where PersonnelID = @p2 group by Month + ' ' + Year, IncomeID order by IncomeID", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p2", textEditIDPersonnel.Text);
            SqlDataReader dr1 = command1.ExecuteReader();
            while (dr1.Read())
            {
                chartControl1.Series["Months"].Points.Add(new DevExpress.XtraCharts.SeriesPoint(dr1[1], dr1[0]));
            }
            
        }

   

        private void simpleButtonSaleSta_Click(object sender, EventArgs e)
        {
            chartControl1.Series["Months"].Points.Clear();
            SqlCommand command = new SqlCommand("select COUNT(CarID) as 'Total Car Sale',Tbl_Income.Month,IncomeID from Tbl_Sale inner join Tbl_Income on Tbl_Sale.IncomeID = Tbl_Income.ID where PersonnelID = @p1 and Year = @p2 group by Tbl_Income.Month, IncomeID order by IncomeID", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            command.Parameters.AddWithValue("@p2", comboBoxYears.Text);
            SqlDataReader dr = command.ExecuteReader();
            while (dr.Read())
            {
                chartControl1.Series["Months"].Points.Add(new DevExpress.XtraCharts.SeriesPoint(dr[1], dr[0]));
            }
            sqlConnect.sqlConnection().Close();
        }

        private void simpleButtonRentalSta_Click(object sender, EventArgs e)
        {
            chartControl1.Series["Months"].Points.Clear();
            SqlCommand command1 = new SqlCommand("select COUNT(CarID) as 'Total Car Sale',Tbl_Income.Month,IncomeID from Tbl_Rent inner join Tbl_Income on Tbl_Rent.IncomeID = Tbl_Income.ID where PersonnelID = @p1 and Year = @p2 group by Tbl_Income.Month, IncomeID order by IncomeID", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            command1.Parameters.AddWithValue("@p2", comboBoxYears.Text);
            SqlDataReader dr1 = command1.ExecuteReader();
            while (dr1.Read())
            {
                chartControl1.Series["Months"].Points.Add(new DevExpress.XtraCharts.SeriesPoint(dr1[1], dr1[0]));
            }
            sqlConnect.sqlConnection().Close();
        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            chartControl1.Series["Months"].Points.Clear();
            SqlCommand command1 = new SqlCommand("select Sum(SalePrice) as 'Total Car Sale Price',Tbl_Income.Month,IncomeID from Tbl_Sale inner join Tbl_Income on Tbl_Sale.IncomeID = Tbl_Income.ID where PersonnelID = @p1 and Year=@p2 group by Tbl_Income.Month, IncomeID order by IncomeID", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            command1.Parameters.AddWithValue("@p2", comboBoxYears.Text);
            SqlDataReader dr1 = command1.ExecuteReader();
            while (dr1.Read())
            {
                chartControl1.Series["Months"].Points.Add(new DevExpress.XtraCharts.SeriesPoint(dr1[1], dr1[0]));
            }
            sqlConnect.sqlConnection().Close();
        }

        private void simpleButton2_Click_1(object sender, EventArgs e)
        {
            chartControl1.Series["Months"].Points.Clear();
            SqlCommand command1 = new SqlCommand("select Sum(RentPrice) as 'Total Car Rent Price',Tbl_Income.Month,IncomeID from Tbl_Rent inner join Tbl_Income on Tbl_Rent.IncomeID = Tbl_Income.ID  where PersonnelID = @p1 and Year=@p2 group by Tbl_Income.Month, IncomeID order by IncomeID", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", textEditIDPersonnel.Text);
            command1.Parameters.AddWithValue("@p2", comboBoxYears.Text);
            SqlDataReader dr1 = command1.ExecuteReader();
            while (dr1.Read())
            {
                chartControl1.Series["Months"].Points.Add(new DevExpress.XtraCharts.SeriesPoint(dr1[1], dr1[0]));
            }
            sqlConnect.sqlConnection().Close();
        }

        private void btnSaveCust_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("insert into Tbl_Customer (Name,Surname,PhoneNumber,Email,SocialSecurityID,BankAccountID) values (@p1,@p2,@p3,@p4,@p5,@p6)",sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1",txtCusNameSale.Text);
            command.Parameters.AddWithValue("@p2",txtCustSurnameSale.Text);
            command.Parameters.AddWithValue("@p3",mskCusPhoneSale.Text);
            command.Parameters.AddWithValue("@p4",txtCustEmailSale.Text);
            command.Parameters.AddWithValue("@p5",mskCustTCSale.Text);
            command.Parameters.AddWithValue("@p6",mskCusBankIDSale.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The customer information has been saved...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);


            SqlCommand command1 = new SqlCommand("select ID from Tbl_Customer where SocialSecurityID=@p1", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", mskCustTCSale.Text);
            SqlDataReader dr = command1.ExecuteReader();
            while (dr.Read())
            {
                txtCustIDSale.Text = dr[0].ToString();
            }
            sqlConnect.sqlConnection().Close();
        }    

        private void comboBoxCarSelect_SelectedIndexChanged(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("select Brand,Model,Year,Price,ID from Tbl_Car where Model=@p1 and VehicleStatus='For Sale'", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", comboBoxCarSelect.Text);
            SqlDataReader dr = command.ExecuteReader();
            while (dr.Read())
            {
                textEditBrandCarSale.Text = dr[0].ToString();
                textEditModelCarSale.Text = dr[1].ToString();
                textEditYearCarSale.Text = dr[2].ToString();
                textEditSalePrice.Text = dr[3].ToString();

            }
            
        }      

        private void btnSaleCar_Click(object sender, EventArgs e)
        {
            int carstock = 0;
            SqlCommand command1 = new SqlCommand("Select ISNULL(Number,0) from Tbl_CarList where CarID=@p1", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", comboBoxCarSelect.SelectedValue);
            SqlDataReader dr = command1.ExecuteReader();
            while (dr.Read())
            {
                carstock = int.Parse(dr[0].ToString());
             
            }
            if (carstock <= 0)
            {
                MessageBox.Show("The car has not been sold...", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                int IncomeID = 0;
                DateTime dateTime = DateTime.Now;
                int Month = dateTime.Month;
                int Year = dateTime.Year;
                SqlCommand command3 = new SqlCommand("select  Tbl_Income.ID from Tbl_Income where Month+''+Year =@p1",sqlConnect.sqlConnection());
                command3.Parameters.AddWithValue("@p1",Month+""+Year);
                SqlDataReader dr3 = command3.ExecuteReader();
                while (dr3.Read())
                {
                    IncomeID = int.Parse(dr3[0].ToString());
                }
            

                SqlCommand command = new SqlCommand("insert into Tbl_Sale (Date,CustomerID,PersonnelID,SalePrice,CarID,IncomeID) values (@p1,@p2,@p3,@p4,@p5,@p6)", sqlConnect.sqlConnection());
                command.Parameters.AddWithValue("@p1", Convert.ToDateTime(labelDate.Text));
                command.Parameters.AddWithValue("@p2", txtCustIDSale.Text);
                command.Parameters.AddWithValue("@p3", textEditIDPersonnel.Text);
                command.Parameters.AddWithValue("@p4", Convert.ToDecimal(textEditSalePrice.Text));
                command.Parameters.AddWithValue("@p5", comboBoxCarSelect.SelectedValue);
                command.Parameters.AddWithValue("@p6", IncomeID);
                command.ExecuteNonQuery();
                sqlConnect.sqlConnection().Close();
          
               
                SqlCommand command2 = new SqlCommand("update Tbl_CarList set Number=Number-1 where CarID=@p1", sqlConnect.sqlConnection());
                command2.Parameters.AddWithValue("@p1", comboBoxCarSelect.SelectedValue);
                command2.ExecuteNonQuery();
                sqlConnect.sqlConnection().Close();
                MessageBox.Show("The car has been sold...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
                saleHistory();

                SqlCommand command4 = new SqlCommand("update Tbl_Income set TotalSale=TotalSale+@p1 where ID=@p2", sqlConnect.sqlConnection());
                command4.Parameters.AddWithValue("@p1", Convert.ToDecimal(textEditSalePrice.Text));
                command4.Parameters.AddWithValue("@p2",IncomeID);
                command4.ExecuteNonQuery();
                sqlConnect.sqlConnection().Close();

                SqlCommand command5= new SqlCommand("update Tbl_Income set Total=Total+@p1 where ID=@p2", sqlConnect.sqlConnection());
                command5.Parameters.AddWithValue("@p1", Convert.ToDecimal(textEditSalePrice.Text));
                command5.Parameters.AddWithValue("@p2", IncomeID);
                command5.ExecuteNonQuery();
                sqlConnect.sqlConnection().Close();
            }                     


        }

        private void btnClearSale_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("select * from Tbl_Customer where SocialSecurityID=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", mskCustTCSale.Text);
            SqlDataReader dr = command.ExecuteReader();
            while (dr.Read())
            {
                txtCustIDSale.Text = dr[0].ToString();
                txtCusNameSale.Text = dr[1].ToString();
                txtCustSurnameSale.Text = dr[2].ToString(); ;
                mskCusPhoneSale.Text = dr[3].ToString();
                txtCustEmailSale.Text= dr[4].ToString();
                mskCustTCSale.Text = dr[5].ToString();
                mskCusBankIDSale.Text = dr[6].ToString();
            }
            sqlConnect.sqlConnection().Close();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("insert into Tbl_Customer (Name,Surname,PhoneNumber,Email,SocialSecurityID,BankAccountID) values (@p1,@p2,@p3,@p4,@p5,@p6)", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", txtRentCustName.Text);
            command.Parameters.AddWithValue("@p2", txtRentCustSurname.Text);
            command.Parameters.AddWithValue("@p3", mskRentCustPhone.Text);
            command.Parameters.AddWithValue("@p4", txtRentCustEmail.Text);
            command.Parameters.AddWithValue("@p5", mslRentCustTC.Text);
            command.Parameters.AddWithValue("@p6", mskRentCustBankID.Text);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The customer information has been saved...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);


            SqlCommand command1 = new SqlCommand("select ID from Tbl_Customer where SocialSecurityID=@p1", sqlConnect.sqlConnection());
            command1.Parameters.AddWithValue("@p1", mslRentCustTC.Text);
            SqlDataReader dr = command1.ExecuteReader();
            while (dr.Read())
            {
                txtRentCustID.Text = dr[0].ToString();
            }
            sqlConnect.sqlConnection().Close();
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand("select * from Tbl_Customer where SocialSecurityID=@p1", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", mslRentCustTC.Text);
            SqlDataReader dr = command.ExecuteReader();
            while (dr.Read())
            {
                txtRentCustID.Text = dr[0].ToString();
                txtRentCustName.Text = dr[1].ToString();
                txtRentCustSurname.Text = dr[2].ToString(); ;
                mskRentCustPhone.Text = dr[3].ToString();
                txtRentCustEmail.Text = dr[4].ToString();
                mslRentCustTC.Text = dr[5].ToString();
                mskRentCustBankID.Text = dr[6].ToString();
            }
            sqlConnect.sqlConnection().Close();
        }
             

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            decimal rentPrice = 0;
            SqlCommand command = new SqlCommand("Select Price from Tbl_Car where Model=@p1 and VehicleStatus='For Rent'", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1",comboBox1.Text);
            SqlDataReader dr = command.ExecuteReader();
            while (dr.Read())
            {
                rentPrice = decimal.Parse(dr[0].ToString());
            }
            sqlConnect.sqlConnection().Close();
            DateTime dtstart = Convert.ToDateTime(dateTimePickerRentStart.Text);
            DateTime dtFinish = Convert.ToDateTime(dateTimePickerRentFinish.Text);
            TimeSpan difference = dtFinish - dtstart;
            int difDays = int.Parse(difference.TotalDays.ToString());
            textEditRentPrice.Text = (Convert.ToDecimal(rentPrice)*difDays).ToString();
        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
            int IncomeID = 0;
            DateTime dateTime = DateTime.Now;
            int Month = dateTime.Month;
            int Year = dateTime.Year;
            SqlCommand command3 = new SqlCommand("select  Tbl_Income.ID from Tbl_Income where Month+''+Year =@p1", sqlConnect.sqlConnection());
            command3.Parameters.AddWithValue("@p1", Month + "" + Year);
            SqlDataReader dr3 = command3.ExecuteReader();
            while (dr3.Read())
            {
                IncomeID = int.Parse(dr3[0].ToString());
            }
            SqlCommand command = new SqlCommand("insert into Tbl_Rent (StartDate,FinishDate,CustomerID,PersonnelID,RentPrice,CarID,IncomeID) values (@p1,@p2,@p3,@p4,@p5,@p6,@p7)", sqlConnect.sqlConnection());
            command.Parameters.AddWithValue("@p1", Convert.ToDateTime(dateTimePickerRentStart.Text));
            command.Parameters.AddWithValue("@p2", Convert.ToDateTime(dateTimePickerRentFinish.Text));
            command.Parameters.AddWithValue("@p3", txtRentCustID.Text);
            command.Parameters.AddWithValue("@p4", textEditIDPersonnel.Text);
            command.Parameters.AddWithValue("@p5", Convert.ToDecimal(textEditRentPrice.Text));
            command.Parameters.AddWithValue("@p6", comboBox1.SelectedValue);
            command.Parameters.AddWithValue("@p7", IncomeID);
            command.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
            MessageBox.Show("The car has been rented...", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            rentedCars();

            SqlCommand command4 = new SqlCommand("update Tbl_Income set TotalRent=TotalRent+@p1 where ID=@p2", sqlConnect.sqlConnection());
            command4.Parameters.AddWithValue("@p1", Convert.ToDecimal(textEditRentPrice.Text));
            command4.Parameters.AddWithValue("@p2", IncomeID);
            command4.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();

            SqlCommand command5 = new SqlCommand("update Tbl_Income set Total=Total+@p1 where ID=@p2", sqlConnect.sqlConnection());
            command5.Parameters.AddWithValue("@p1", Convert.ToDecimal(textEditRentPrice.Text));
            command5.Parameters.AddWithValue("@p2", IncomeID);
            command5.ExecuteNonQuery();
            sqlConnect.sqlConnection().Close();
        }             
    }
}